version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=btata
      - DB_NAME=matching_db
    depends_on:
      - db
    command: sh -c "npm install && npm run build:ts && npm start" # Ensure the app waits for dependencies

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: btata
      MYSQL_DATABASE: matching_db

    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  db_data: # Volume definition for persisting data
  
   

 