version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: pokechakucha-users-db
    environment:
      POSTGRES_USER: pokechakucha
      POSTGRES_PASSWORD: pokechakucha123
      POSTGRES_DB: pokechakucha_users
    ports:
      - "5432:5432"
    volumes:
      - pokechakucha_users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokechakucha"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pokechakucha_users_data:
